mongodb:
  primary:
    host: localhost
    port: 27017
    database: productCatalogA
    username: myUserAdmin
    password: mongoadmin
    authentication-database: admin
  secondary:
    host: localhost
    port: 27017
    database: productCatalogB
    username: myUserAdmin
    password: mongoadmin
    authentication-database: admin