elastic:
  scheme: http
  hostname: localhost
  port: 9200
  maxItemCount: 10000
  autosuggestion:
   defaultRange: 10

server:
  port: 3004

---

spring:
  profiles: docker
elastic:
  hostname: epuakhaw1360ieat.kyiv.epam.com
