eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/

management:
  security:
    enabled: false

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:3001/eureka/
