spring:
  application:
    name: contact
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  cloud:
    config:
      uri: http://localhost:3000
      fail-fast: true

---

spring:
  profiles: docker
  cloud:
    config:
      uri: http://config:3000
---